# Generated by Django 3.0 on 2019-12-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('happy', models.IntegerField()),
                ('pleasure', models.IntegerField()),
                ('hate', models.IntegerField()),
                ('sadness', models.IntegerField()),
                ('anger', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('diary_date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfeeling', models.CharField(max_length=20)),
                ('feelings', models.CharField(max_length=300)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cal.Event')),
            ],
        ),
    ]
